# Generated by Django 3.0.6 on 2020-06-01 04:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200531_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
