# Generated by Django 3.0.6 on 2020-05-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200125_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='bio',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='ppoi',
        ),
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
        migrations.RemoveField(
            model_name='image',
            name='ppoi',
        ),
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
