# Generated by Django 3.0.6 on 2020-05-29 08:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200529_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='pic',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
