# Generated by Django 2.2 on 2020-08-01 07:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagecontent_imagecontenttranslation_page_pagecontent_pagecontenttranslation_pagetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
    ]
