# Generated by Django 2.2 on 2020-08-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200805_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='biotranslation',
            name='cv_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
