# Generated by Django 2.2.3 on 2019-07-15 01:46

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='pic',
            field=versatileimagefield.fields.VersatileImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bio',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
