# Generated by Django 2.2.3 on 2019-07-15 02:01

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190715_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='pic_ppoi'),
        ),
    ]
