# Generated by Django 2.2.3 on 2019-07-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190715_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(),
        ),
    ]
